# Continuous integration with travis
language: r
sudo: required

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r: devel
    - os: linux
      dist: precise
      sudo: false
      r: release



# cache packages to speed up builds
cache: packages

# Check code test coverage
r_packages:
 - covr
after_success:
 - Rscript -e 'library(covr);codecov()'
